### ISSUE TITLE
не працуе ў OTTplayer’ы

### ISSUE THREAD

**Issue by yalov** [mashrum/a1_m3u#4]
Цікава, што на розных праграмах ды аперацыйных сістэмах гэты url-плэйліст (https://clck.ru/TxLgK) паводзіць сябе па-рознаму, праграммы здолелі зпампаваць плэйліст, але:

* Windows:
  * PotPlayer: 
    * ёсць лагатыпы, але не іграе каналы 
    * іграе каналы, калі наладзіць udp на роўтэры ды дадаць ip udp-сервера у спасылках: http://192.168.1.1:4022/udp/A.B.C.D:P
  * OTTplayer (https://ottplayer.es)
    * няма ні лагатыпаў, ні EPG, ні відэа. 
    * Тое самае з мадыфікаваным udp-плэйлістом
* Android:
  * LazyIptv:    
    * іграе каналы, але няма некаторых лагатыпаў і некаторых EPG (https://i.imgur.com/zFEO1Mj.jpeg)
    * Тое самае з мадыфікаваным udp-плэйлістом
  * OTTplayer (https://ottplayer.es)
    * няма лагатыпаў, няма EPG, ёсць відэа. 

Якія праграмы выкарыстоўваеш, @mashrum ? 
Ці працуе у цябе гэты плэйліст у OTTplayer’ы (https://ottplayer.es) ?

**Comment by mashrum** [comment]
Гэта дзіўна.
KODI (кампанент PVR IPTV Simple Client) https://kodi.tv
ProgTV https://play.google.com/store/apps/details?id=com.progdvb.progtva

Іншыя плэеры умеюць праіграваць, але інтерфейсы і магчымасці абы што як па мне. Але не крытыкую.

LazyTV
вось два лагатыпа, адзін паказвае, а другі не :)
крыніца агульная, фармат агульны. Праблема ў прайгравальніку. Нешта з ім не то.
https://resizer.voka.tv/rosing-voka-production/c74bcd743a364acddf76_250x250c.png
https://resizer.voka.tv/rosing-voka-production/61fbba71524f49fb956c_250x250c.png

UDP праз router
нешта не тое з наладамі. Нічога рукамі не прапісваю на роўтэры.

**Comment by mashrum** [comment]
Правярайце на роўтэры наяўнасць кампанента "IGMP Proxy Services", можа вам і дапаможа.
